- name: install packages
  with_items:
    - ufw
  package:
    name: '{{ item }}'
    state: present
  tags:
    - firewall

- name: write before
  when: firewall_before_rules is not none
  notify:
    - reload firewall
  copy:
    content: '{{ firewall_before_rules }}'
    dest: /etc/ufw/before.rules
  tags:
    - firewall

- name: write after
  when: firewall_after_rules is not none
  notify:
    - reload firewall
  copy:
    content: '{{ firewall_after_rules }}'
    dest: /etc/ufw/after.rules
  tags:
    - firewall

- name: write before6
  when: firewall_before6_rules is not none
  notify:
    - reload firewall
  copy:
    content: '{{ firewall_before6_rules }}'
    dest: /etc/ufw/before6.rules
  tags:
    - firewall

- name: write after6
  when: firewall_after6_rules is not none
  notify:
    - reload firewall
  copy:
    content: '{{ firewall_after6_rules }}'
    dest: /etc/ufw/after6.rules
  tags:
    - firewall

- name: policy incoming
  ufw:
    direction: incoming
    policy: '{{ firewall_incoming_policy }}'
  tags:
    - firewall

- name: policy outgoing
  ufw:
    direction: outgoing
    policy: '{{ firewall_outgoing_policy }}'
  tags:
    - firewall

- name: allow ips
  with_items: '{{ firewall_allow_ips }}'
  ufw:
    rule: allow
    src: '{{ item }}'
    proto: any
  tags:
    - firewall

- name: define ssh
  when: firewall_ssh_enabled
  ufw:
    rule: '{{ firewall_ssh_rule }}'
    port: '{{ firewall_ssh_port }}'
    proto: any
  tags:
    - firewall

- name: define https
  when: firewall_https_enabled
  ufw:
    rule: '{{ firewall_https_rule }}'
    port: '{{ firewall_https_port }}'
    proto: any
  tags:
    - firewall

- name: define http
  when: firewall_http_enabled
  ufw:
    rule: '{{ firewall_http_rule }}'
    port: '{{ firewall_http_port }}'
    proto: any
  tags:
    - firewall

- name: define rules
  with_items: '{{ firewall_rules }}'
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto | default("any") }}'
    direction: '{{ item.direction | default("in") }}'
    from_ip: '{{ item.from_ip | default("any") }}'
    from_port: '{{ item.from_port | default("") }}'
    to_ip: '{{ item.to_ip | default("any") }}'
    to_port: '{{ item.to_port | default("") }}'
  tags:
    - firewall

- name: define logging
  ufw:
    logging: '{{ firewall_logging }}'
  tags:
    - firewall

- name: enable ufw
  ufw:
    state: enabled
  tags:
    - firewall
